Make build scripts stop on first error. (#6)
Improve the current build scripts by making them stop on the first error:

- Prepend `set -eu` to all build (shell) scripts.
- Still allow Mecrisp Stellaris to build on non-Linux platforms by skipping the Linux port unless a Linux assembler is available.
- Rewrite error handling in the `build() { ... }` function.
- Fix the Palanquin ports by creating the `precompiled/` directories as needed.

Reviewed-on: https://codeberg.org/clausecker/mecrisp-stellaris/pulls/6
Co-authored-by: Jan Bramkamp <crest@rlwinm.de>
Co-committed-by: Jan Bramkamp <crest@rlwinm.de>

diff --git a/mecrisp-stellaris-source/assemble b/mecrisp-stellaris-source/assemble
--- a/mecrisp-stellaris-source/assemble
+++ b/mecrisp-stellaris-source/assemble
@@ -1,14 +1,31 @@
 #!/bin/sh
+set -eu
 
 build() {
-	mkdir -p ../"$1"
-	( cd "$1" || return
-	make clean all
-	ls -l *.bin
-	md5sum *.bin
-	[ -f *.bin ] && cp *.bin ../../"$1"/
-	[ -f *.hex ] && cp *.hex ../../"$1"/
-	[ -f *.srec ] && cp *.srec ../../"$1"/
+	(
+		port="${1:?}"
+		cd "${port:?}"
+
+		mkdir -p "../../${port:?}"
+		make clean all
+
+		set -- *.bin
+		if [ -f "$1" ]; then
+			ls -l -- "$@"
+			md5sum -- "$@"
+			cp -- "$@" "../../${port:?}/"
+		fi
+
+		set -- *.hex
+		if [ -f "$1" ]; then
+			cp -- "$@" "../../${port:?}/"
+		fi
+
+		set -- *.srec
+		if [ -f "$1" ]; then
+			cp -- "$@" "../../${port:?}/"
+		fi
+
 	)
 }
 
@@ -327,15 +344,19 @@ cd ..
 
 cd mecrisp-stellaris-source
 
-cd linux
-./assemble
-cp mecrisp-stellaris-linux ../../linux
-cd ..
+if ! which arm-linux-gnueabi-as; then
+	echo 'Install missing arm-linux-gnueabi-as command to build the Linux port.' >&2
+else
+	cd linux
+	./assemble
+	cp mecrisp-stellaris-linux ../../linux
+	cd ..
 
-cd linux-ra
-./assemble
-cp mecrisp-stellaris-linux ../../linux-ra
-cd ..
+	cd linux-ra
+	./assemble
+	cp mecrisp-stellaris-linux ../../linux-ra
+	cd ..
+fi
 
 cd freebsd-ra
 ./assemble
